---
title: "INPE Data Processing"
author: "Shai Vaz"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
# Data Wrangling
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(arrow)
library(lubridate)

# Personal functions
```

# Importing data as Arrow dataset


We import using the arrow library, and save as parquet files for fast retrieval.

## All Satellites

```{r}
dataset_csv_path = "../Inputs/fires/todos_sats/csv/"
dataset_parquet_path = "../Inputs/fires/todos_sats/parquet"

# Import csv
fires_all_sats = open_csv_dataset(
  dataset_csv_path,
  col_types = schema(
    numero_dias_sem_chuva = double(),
    precipitacao = double(),
    risco_fogo = double(),
    id_area_industrial = double(),
    frp = double()
  ) 
)

# Create Year and Month Columns
fires_all_sats <- fires_all_sats |> 
  mutate(
    year = year(data_pas),
    month = month(data_pas)
  )

# Export as Parquet
write_dataset(
  fires_all_sats,
  path = dataset_parquet_path,
  format = "parquet",
  partitioning = c("year")
)
```

Finally, we reopen with parquet files.

```{r}
# Reopen dataset from parquet file 
dataset_parquet_path = "../Inputs/fires/todos_sats/parquet"
fires_all_sats <- open_dataset(
  dataset_parquet_path,
  format = "parquet"
)
```

## Reference Satellite

```{r}
dataset_csv_path = "../Inputs/fires/sat_ref/csv/"
dataset_parquet_path = "../Inputs/fires/sat_ref/parquet"

# Import csv
fires_ref_sat = open_csv_dataset(
  dataset_csv_path,
  col_types = schema(
    id_bdq = string()
  ) 
)

# Create Year and Month Columns
fires_ref_sat <- fires_ref_sat |> 
  mutate(
    year = year(data_pas),
    month = month(data_pas)
  )

# Export as Parquet
write_dataset(
  fires_ref_sat,
  path = dataset_parquet_path,
  format = "parquet",
  partitioning = c("year")
)
```

Reopen from parquet.

```{r}
# Reopen dataset from parquet file
dataset_parquet_path = "../Inputs/fires/sat_ref/parquet"
fires_ref_sat <- open_dataset(
  dataset_parquet_path,
  format = "parquet"
)
```

## Sisam Data


